export const BUILT_IN_CARDS = [
    // Breath & Relaxation (1–20)
    {id:1, front:"What two pillars instantly improve voice?", back:"Relaxation + diaphragmatic breath."},
    {id:2, front:"Where should you feel expansion when inhaling?", back:"Ribs widening around the middle body."},
    {id:3, front:"What’s the diaphragm doing on inhale?", back:"Flattening downward like an inverted dome."},
    {id:4, front:"Quick cue to open the throat?", back:"Start a yawn, then speak before it breaks."},
    {id:5, front:"Daily breath drill in bed length?", back:"About 5 minutes night + 5 minutes morning."},
    {id:6, front:"What kills good tone fastest?", back:"Tension in throat, jaw, or tongue."},
    {id:7, front:"Where should muscles be relaxed for speaking?", back:"From the waist up, especially above the collarbone."},
    {id:8, front:"Best exhale control location?", back:"The diaphragm, not the throat."},
    {id:9, front:"Simple airflow test for control?", back:"Candle test: steady exhale without flicker."},
    {id:10, front:"What sensation should the chest have on breath?", back:"Riding on the air—floating, not held."},
    {id:11, front:"What’s the quick reset before speaking?", back:"Jaw drop + two rib-expansion breaths."},
    {id:12, front:"Name the three tone fundamentals.", back:"Breath control, relaxation, resonance."},
    {id:13, front:"How to avoid shoulder-lift breathing?", back:"Lift chest high, keep shoulders down."},
    {id:14, front:"Why vary emphasis, speed, and pitch?", back:"To arrest attention and carry meaning."},
    {id:15, front:"What is ‘half breathing’?", back:"Top-of-chest breathing without diaphragmatic support."},
    {id:16, front:"Where should the throat be in good production?", back:"Open; think ‘no throat.’"},
    {id:17, front:"Feeling cue for tone direction.", back:"Tone comes in & up (yawn/cry feeling)."},
    {id:18, front:"Reserve rule while speaking.", back:"Keep ample breath in the lungs—never run empty."},
    {id:19, front:"Why rest and health matter to voice?", back:"Vitality and resonance reflect bodily condition."},
    {id:20, front:"Daily attitude that upgrades tone?", back:"Enthusiasm and sincere feeling."},

    // Tongue, Jaw, Teeth (21–36)
    {id:21, front:"Where should the tongue rest at ease?", back:"Floor of mouth; tip lightly behind lower teeth."},
    {id:22, front:"Key danger with back-of-tongue use?", back:"It tugs the larynx and tightens the throat."},
    {id:23, front:"Best part of tongue for crisp speech?", back:"The agile tip—the first quarter inch."},
    {id:24, front:"How to make L bright and clean?", back:"Tip behind upper teeth; air flows over the tongue."},
    {id:25, front:"Jaw rule during drills?", back:"Loose, released; only minimal movement."},
    {id:26, front:"Quick jaw/tongue warmup.", back:"Tongue out/in, up/down, side/side, small circles."},
    {id:27, front:"EE–AH drill purpose?", back:"Still jaw, active tongue; switch forward/back vowels."},
    {id:28, front:"Teeth spacing cue.", back:"Keep a blueberry’s worth of space; don’t clench."},
    {id:29, front:"Where should air flow on L’s?", back:"Up and over the tongue (not crushed by it)."},
    {id:30, front:"Lazy-tongue symptom in words like ‘mountain’?", back:"Dropping t’s: ‘moun’n.’"},
    {id:31, front:"Fix for sloppy consonants (t,d,th,n,ch,j,z)?", back:"Press tip to roof just behind teeth—snappy release."},
    {id:32, front:"Why trill R?", back:"Strengthens tongue tip; keeps back relaxed."},
    {id:33, front:"‘Pen between teeth’ drill helps what?", back:"Enunciation while keeping jaw still."},
    {id:34, front:"Talk vs chill tongue landmark (cue)", back:"Talking: tip up/right molar; rest: bottom left teeth."},
    {id:35, front:"When sound lives only in one inner cheek?", back:"Balance resonance to both sides; invite the other cheek."},
    {id:36, front:"Quick jaw release trick.", back:"Two gentle yawns; feel jaw melt down."},

    // Resonance & Agility (37–58)
    {id:37, front:"What is resonance in practice?", back:"Loudness without push—head, face, and chest vibrating."},
    {id:38, front:"Two best ‘easy resonance’ drills.", back:"Lip trills and NG sirens."},
    {id:39, front:"Where to feel NG?", back:"Soft palate contact; buzz between nose and forehead."},
    {id:40, front:"Why hum ‘mmm’?", back:"Connects facial buzz to vowels (ma, me, mo)."},
    {id:41, front:"Simple 5‑min tune‑up step 1.", back:"Jaw drop + rib breaths (sss then tss bursts)."},
    {id:42, front:"Simple 5‑min tune‑up step 2.", back:"Hums + sirens (NG or lip trill)."},
    {id:43, front:"Simple 5‑min tune‑up step 3.", back:"EE–AH + quick tongue stretch."},
    {id:44, front:"Simple 5‑min tune‑up step 4.", back:"Lah‑Lay‑Lee‑Low‑Loo + tongue twisters."},
    {id:45, front:"Simple 5‑min tune‑up step 5.", back:"Resonance reset: easy ‘yah’ + final hum‑to‑vowel."},
    {id:46, front:"What’s straw phonation good for?", back:"Relaxed cords, smooth transitions, less strain."},
    {id:47, front:"Falsetto practice gives what?", back:"Brightness in ordinary speaking tones."},
    {id:48, front:"How to think while exhaling for resonance?", back:"Imagine you’re still inhaling—keep head spaces open."},
    {id:49, front:"Where should you feel lip trill?", back:"Forward buzz on lips; even airflow, no push."},
    {id:50, front:"‘Yah‑yah‑yah’ goal.", back:"Open, yawny resonance with jaw loose."},
    {id:51, front:"Why practice joyful poetry aloud?", back:"It imprints happy overtones into your voice."},
    {id:52, front:"Head vs chest vibration check.", back:"Palms on head and chest while humming; feel both."},
    {id:53, front:"What gives carrying power beyond volume?", back:"Rich resonance + sincere meaning."},
    {id:54, front:"How to speak ‘forward’?", back:"Word in the mouth; tone flows freely through the nose."},
    {id:55, front:"Nasal resonance benefit.", back:"Brightness and carry at distance (without nasality)."},
    {id:56, front:"Best vowel practice idea.", back:"Open, distinct vowels; lips shape fully; jaw relaxed."},
    {id:57, front:"Pitch habit to avoid monotone.", back:"Let pitch flow up and down naturally."},
    {id:58, front:"Volume vs loudness—what’s the key?", back:"Meaning + resonance create distance, not shouting."},

    // Delivery & Rhetoric (59–76)
    {id:59, front:"Four-part speech plan.", back:"Attention, confidence, facts, motive."},
    {id:60, front:"Core delivery question set (4).", back:"Stress key words? Vary pitch? Vary rate? Pause smart?"},
    {id:61, front:"How to sound conversational on stage?", back:"Answer imagined questions: “You ask… I’ll tell you.”"},
    {id:62, front:"Why pause before/after key ideas?", back:"Creates punch and clarity."},
    {id:63, front:"Instant clarity boost in conversation.", back:"Speak slower than you think you should."},
    {id:64, front:"Projection image.", back:"Imagine speaking from a mountain—forward, effortless."},
    {id:65, front:"Audience connection basics (3).", back:"Look at them, vary rhythm, embody good cheer."},
    {id:66, front:"Best way to kill filler words?", back:"Slow pace + purposeful pauses."},
    {id:67, front:"How to make vowels carry?", back:"Open them; shape with lips; let jaw drop."},
    {id:68, front:"Place to strike emphatic ideas.", back:"Tip of tongue taps behind teeth—light, elastic."},
    {id:69, front:"Mental cue to swat anxiety.", back:"“I’m thoroughly relaxed.” Repeat until body follows."},
    {id:70, front:"Memorization triad.", back:"Impression, repetition, association."},
    {id:71, front:"When progress stalls (plateau)?", back:"Persist—lift-off often comes suddenly."},
    {id:72, front:"Sincere emotion effect on tone.", back:"Warms and humanizes delivery."},
    {id:73, front:"Best time to practice breath on the go.", back:"Walking, through doorways, odd office moments."},
    {id:74, front:"Why carry chest high, not shoulders?", back:"High chest aids breath; high shoulders choke throat."},
    {id:75, front:"The 4 G’s motto.", back:"Grace, gumption, grit, guts."},
    {id:76, front:"What is ‘voice charm’?", back:"A product of resonance, bright overtones, and joy."},

    // Drills & Twisters (77–90)
    {id:77, front:"Core vowel ladder to drill.", back:"mate–met–mit–moot; rack–reck–rick–rock–rook; bah–boil."},
    {id:78, front:"Singing consonants trio.", back:"L, N, M—let them sing."},
    {id:79, front:"Two classic twisters to sharpen diction.", back:"Unique New York; Red leather, yellow leather."},
    {id:80, front:"NG word chain for nasal ring.", back:"Singing, bringing, flinging, hanging…"},
    {id:81, front:"R lip/tongue agility drill.", back:"tra, tre, tri, tro, tru; bra, bre, bri, bro, bru."},
    {id:82, front:"M/N resonance stream.", back:"meeneemeenee—keep hum continuous while changing vowels."},
    {id:83, front:"No/Man lips drill purpose.", back:"Exaggerate lip motion for clearer vowels."},
    {id:84, front:"Count-on-one-breath trains what?", back:"Diaphragmatic control without throat squeeze."},
    {id:85, front:"Straw/lip-trill glide intent.", back:"Even, effortless airflow across range."},
    {id:86, front:"Vocal fry utility.", back:"Encourages gentle cord closure; adds weight without strain."},
    {id:87, front:"Head↔fry↔chest toggles train…", back:"Smooth register transitions with zero grab."},
    {id:88, front:"‘Yah’ technique jaw rule.", back:"Jaw still; tongue forward on clear ‘yuh.’"},
    {id:89, front:"‘Uh‑uh’ staccato focuses what?", back:"Inner edges—quick pin‑prick taps, no ‘h.’"},
    {id:90, front:"Driving-friendly practice idea.", back:"Hum lightly with resonance focus—not volume."},

    // Quick Habits & Cues (91–100)
    {id:91, front:"Pre-talk 30‑second reset.", back:"Jaw melt, two rib breaths, one ‘mmm→maaa.’"},
    {id:92, front:"Forward focus landmark.", back:"Right nostril area; feel tone project there."},
    {id:93, front:"Where should vowels live?", back:"Front of the mouth—ringing just behind top teeth."},
    {id:94, front:"If tension spikes mid-speech…", back:"Slow down, breathe, reset jaw, continue."},
    {id:95, front:"Simple daily micro‑routine length.", back:"5–10 minutes of mindful drills."},
    {id:96, front:"Best imitation practice.", back:"Parrot a speaker you admire—tone, rhythm, syllables."},
    {id:97, front:"Most important speed rule.", back:"Speak slower; clarity beats haste."},
    {id:98, front:"One sentence that centers posture.", back:"Chin in, crown high, chest up—shoulders down."},
    {id:99, front:"Airflow mantra.", back:"Relaxation = no restriction of airflow."},
    {id:100, front:"Ultimate north star for voice.", back:"Effortless resonance riding on steady breath."},
  ];
